/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';

/* TODO APP */
export const TODO_GET_LIST = 'TODO_GET_LIST';
export const TODO_GET_LIST_SUCCESS = 'TODO_GET_LIST_SUCCESS';
export const TODO_GET_LIST_ERROR = 'TODO_GET_LIST_ERROR';
export const TODO_GET_LIST_WITH_FILTER = 'TODO_GET_LIST_WITH_FILTER';
export const TODO_GET_LIST_WITH_ORDER = 'TODO_GET_LIST_WITH_ORDER';
export const TODO_GET_LIST_SEARCH = 'TODO_GET_LIST_SEARCH';
export const TODO_ADD_ITEM = 'TODO_ADD_ITEM';
export const TODO_ADD_ITEM_SUCCESS = 'TODO_ADD_ITEM_SUCCESS';
export const TODO_ADD_ITEM_ERROR = 'TODO_ADD_ITEM_ERROR';
export const TODO_SELECTED_ITEMS_CHANGE = 'TODO_SELECTED_ITEMS_CHANGE';

/* PROJECT APP */
export const PROJECT_GET_LIST = 'PROJECT_GET_LIST';
export const PROJECT_GET_LIST_SUCCESS = 'PROJECT_GET_LIST_SUCCESS';
export const PROJECT_GET_LIST_ERROR = 'PROJECT_GET_LIST_ERROR';
export const PROJECT_ADD = 'PROJECT_ADD';
export const PROJECT_SAVE = 'PROJECT_SAVE';
export const PROJECT_SAVE_SUCCESS = 'PROJECT_SAVE_SUCCESS';
export const PROJECT_SAVE_ERROR = 'PROJECT_SAVE_ERROR';
export const PROJECT_EDIT = 'PROJECT_EDIT';
export const PROJECT_EDIT_SUCCESS = 'PROJECT_EDIT_SUCCESS';
export const PROJECT_EDIT_ERROR = 'PROJECT_EDIT_ERROR';

/* MATERIALS */
export const MATERIALS_GET = 'MATERIALS_GET';
export const MATERIALS_GET_SUCCESS = 'MATERIALS_GET_SUCCESS';
export const MATERIALS_GET_ERROR = 'MATERIALS_GET_ERROR';
